# Generated by Django 5.1.7 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='sol',
            field=models.CharField(default='test_sol', max_length=100),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='voc',
            field=models.CharField(default='test_voc', max_length=100),
        ),
    ]
