# Generated by Django 5.1.7 on 2025-04-09 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc_test", "0003_rename_sol_vocabulary_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user_answering",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
