# Generated by Django 5.1.7 on 2025-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc_test", "0004_alter_quizsession_id_alter_user_answering_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="name",
            field=models.CharField(default="default_session", max_length=100),
        ),
    ]
