# Generated by Django 5.2 on 2025-04-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voc_test', '0007_vocabulary_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary_table',
            old_name='voc_list',
            new_name='voc_id_list',
        ),
    ]
